version: '3'
services:

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=beverage
      - POSTGRES_USER=maria
      - POSTGRES_HOST_AUTH_METHOD=trust
#    volumes:
#      - ./db/sql:/docker-entrypoint-initdb.d

  app:
    build:
      context: app
    ports:
      - 8080:8080
    depends_on:
        - db
